# -*- coding: utf-8 -*-
"""Entrega3_ProyectoFinal_APO3_MovementAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKCea--3k1tDN5q4qV8HQyjxmScabi5u

# **Entrega 3 - Proyecto Final APO 3**

## **Sistema de Anotación de Video para Análisis de Actividades Humanas**

$$$$
**Integrantes del grupo:**

*   Mariana De La Cruz - A00399618
*   Valentina Gómez - A00398790
*   Alexis Delgado - A00399176
*   Juan Camilo Amorocho - A00399789

### **Contexto**

El proyecto busca aplicar metodologías de analítica de datos y aprendizaje automático para resolver un problema real mediante el procesamiento y análisis de información visual.

El análisis del movimiento humano constituye un desafío técnico que implica la correcta detección y seguimiento de las articulaciones del cuerpo a partir de secuencias de video. Para abordar este reto, se utilizarán herramientas de visión por computadora, que permiten identificar puntos clave del cuerpo y extraer información relevante para su posterior procesamiento.


Este proyecto busca aplicar de manera práctica la metodología CRISP-DM, siguiendo las fases de comprensión, preparación, modelado, evaluación e implementación, con el fin de desarrollar un sistema capaz de reconocer actividades humanas básicas a partir de datos capturados por cámara. De esta forma, se pretende lograr una solución técnica completa que integre todos los pasos del proceso de análisis y clasificación de movimiento, desde la captura de datos hasta la generación de resultados interpretables.

### **Definición del problema**

A pesar de los avances existentes en el reconocimiento de actividades humanas, los sistemas actuales enfrentan dificultades para realizar una clasificación precisa y estable de movimientos en tiempo real, especialmente en condiciones variables de luz, distancia, velocidad y entorno. Estas limitaciones reducen la aplicabilidad de los modelos en escenarios cotidianos o educativos.

En este proyecto se plantea el desarrollo de una herramienta de software capaz de analizar actividades humanas básicas como caminar hacia la cámara, caminar de regreso, girar, sentarse y ponerse de pie mediante el seguimiento de articulaciones clave del cuerpo.

El sistema utilizará la cámara para capturar el movimiento, procesar la información a través de herramientas como MediaPipe y landmarks, extraer características relevantes (velocidades, ángulos e inclinaciones) y finalmente clasificar la actividad ejecutada utilizando modelos de aprendizaje supervisado.

El reto principal consiste en combinar de forma eficiente la detección de pose con la clasificación automática, garantizando que el sistema funcione en tiempo real y sea capaz de adaptarse a diferentes usuarios y condiciones de grabación.

## **Reducción de Dimensionalidad con PCA**

En la Entrega 2 se obtuvieron resultados excelentes con los tres modelos entrenados:
- Random Forest: 100% accuracy
- SVM: 100% accuracy  
- XGBoost: 88.9% accuracy

Sin embargo, el dataset cuenta con 12 características numéricas, lo que podría generar:
- Redundancia en la información capturada
- Posible sobreajuste (overfitting) por el tamaño limitado del dataset (86 observaciones)
- Complejidad computacional innecesaria

El objetivo de esta entrega es aplicar **PCA (Principal Component Analysis)** para:
1. Reducir la dimensionalidad del espacio de características
2. Identificar cuánta varianza explican los componentes principales
3. Generar un dataset reducido que conserve la mayor información posible
4. Reentrenar los modelos y comparar el rendimiento

### **Parte 1: Análisis de Componentes Principales (PCA)**
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import joblib
from google.colab import drive
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

from google.colab import drive
drive.flush_and_unmount()

!rm -rf /content/drive

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from sklearn.decomposition import PCA
import joblib
import os

BASE_PATH_E3 = "/content/drive/MyDrive/APO3_EntregaFinal/Entrega3"
DATASETS_PATH = os.path.join(BASE_PATH_E3, "datasets")
RESULTADOS_PATH_E3 = os.path.join(BASE_PATH_E3, "resultados")

# Crear estructura de carpetas para Entrega 3
os.makedirs(DATASETS_PATH, exist_ok=True)
os.makedirs(RESULTADOS_PATH_E3, exist_ok=True)

print("Estructura de carpetas para Entrega 3 creada correctamente.")
print(f"Datasets: {DATASETS_PATH}")
print(f"Resultados: {RESULTADOS_PATH_E3}")

!ls /content/drive/MyDrive/APO3_EntregaFinal

import pandas as pd
from sklearn.preprocessing import LabelEncoder

print("CARGANDO DATASET NORMALIZADO DE ENTREGA 2")

# Cargar el dataset normalizado generado en Entrega 2
csv_norm_path = "/content/drive/MyDrive/APO3_EntregaFinal/Entrega2/resultados/dataset_normalizado.csv"
df_norm_e3 = pd.read_csv(csv_norm_path)

print(f"\nDataset cargado correctamente")
print(f"Dimensiones: {df_norm_e3.shape}")
print(f"Categorías: {df_norm_e3['categoria'].unique()}")
print(f"Características numéricas: {len(df_norm_e3.select_dtypes(include=['float64', 'int64']).columns)}")

# Separar características y etiquetas
X_full = df_norm_e3.drop(columns=["categoria"])
y_full = df_norm_e3["categoria"]

# Codificar etiquetas
label_encoder_e3 = LabelEncoder()
y_encoded_e3 = label_encoder_e3.fit_transform(y_full)

print(f"\nCaracterísticas disponibles ({X_full.shape[1]}):")
for i, col in enumerate(X_full.columns, 1):
    print(f"   {i:2d}. {col}")

print("APLICANDO PCA - ANÁLISIS DE COMPONENTES PRINCIPALES")

# Aplicar PCA con todos los componentes posibles
n_components = min(X_full.shape[0], X_full.shape[1])  # Máximo posible
pca_full = PCA(n_components=n_components, random_state=42)
X_pca_full = pca_full.fit_transform(X_full)

# Calcular varianza explicada
varianza_explicada = pca_full.explained_variance_ratio_
varianza_acumulada = np.cumsum(varianza_explicada)

print(f"\nPCA aplicado exitosamente")
print(f"Componentes calculados: {len(varianza_explicada)}")
print(f"Varianza explicada por componente:")

for i, (var, cum) in enumerate(zip(varianza_explicada, varianza_acumulada), 1):
    print(f"   PC{i:2d}: {var*100:6.2f}% (acumulado: {cum*100:6.2f}%)")

"""Al aplicar PCA al conjunto completo de características, pude observar que el dataset tiene una estructura muy definida y que varias variables están claramente correlacionadas entre sí. El primer componente explica alrededor del 37% de la variabilidad, y con los primeros cinco o seis componentes ya se supera el 80%, lo que confirma que gran parte de la información se concentra en pocas dimensiones.

En general, el PCA mostró que las métricas biomecánicas y visuales que se extrajeron son consistentes y no contienen ruido significativo. También evidencia que existen redundancias naturales en los movimientos corporales. Estos resultados respaldan que los datos son adecuados para entrenar modelos supervisados y que la estructura del dataset facilita la separación entre posturas y actividades.
"""

print("GENERANDO VISUALIZACIONES DE VARIANZA EXPLICADA")

# Configuración de estilo
sns.set(style="whitegrid", palette="deep")

# Figura
fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# (Varianza por Componente)
axes[0].bar(range(1, len(varianza_explicada) + 1), varianza_explicada * 100,
            color='steelblue', alpha=0.8, edgecolor='black')
axes[0].plot(range(1, len(varianza_explicada) + 1), varianza_explicada * 100,
             'ro-', linewidth=2, markersize=8)
axes[0].set_xlabel('Componente Principal', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Varianza Explicada (%)', fontsize=12, fontweight='bold')
axes[0].set_title('Scree Plot - Varianza por Componente', fontsize=14, fontweight='bold')
axes[0].grid(axis='y', alpha=0.5)
axes[0].set_xticks(range(1, len(varianza_explicada) + 1))

# Varianza Acumulada
axes[1].plot(range(1, len(varianza_acumulada) + 1), varianza_acumulada * 100,
             'go-', linewidth=3, markersize=10, markerfacecolor='lightgreen')
axes[1].axhline(y=80, color='red', linestyle='--', linewidth=2, label='80% Varianza')
axes[1].axhline(y=90, color='orange', linestyle='--', linewidth=2, label='90% Varianza')
axes[1].axhline(y=95, color='purple', linestyle='--', linewidth=2, label='95% Varianza')
axes[1].fill_between(range(1, len(varianza_acumulada) + 1), varianza_acumulada * 100,
                      alpha=0.3, color='green')
axes[1].set_xlabel('Número de Componentes', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Varianza Acumulada (%)', fontsize=12, fontweight='bold')
axes[1].set_title('Varianza Acumulada vs Número de Componentes', fontsize=14, fontweight='bold')
axes[1].legend(loc='lower right', fontsize=10)
axes[1].grid(True, alpha=0.5)
axes[1].set_xticks(range(1, len(varianza_acumulada) + 1))
axes[1].set_ylim([0, 105])

# Contribución de Variables a PC1 y PC2
loadings = pca_full.components_[:2].T * np.sqrt(pca_full.explained_variance_[:2])
feature_names = X_full.columns

# Crear DataFrame para facilitar visualización
loadings_df = pd.DataFrame(
    loadings,
    columns=['PC1', 'PC2'],
    index=feature_names
)

# Ordenar por contribución absoluta a PC1
loadings_df['abs_PC1'] = loadings_df['PC1'].abs()
loadings_df_sorted = loadings_df.sort_values('abs_PC1', ascending=True)

y_pos = np.arange(len(loadings_df_sorted))
axes[2].barh(y_pos, loadings_df_sorted['PC1'], color='steelblue', alpha=0.7, label='PC1')
axes[2].barh(y_pos, loadings_df_sorted['PC2'], color='coral', alpha=0.7, label='PC2')
axes[2].set_yticks(y_pos)
axes[2].set_yticklabels(loadings_df_sorted.index, fontsize=9)
axes[2].set_xlabel('Contribución (Loading)', fontsize=12, fontweight='bold')
axes[2].set_title('Contribución de Variables a PC1 y PC2', fontsize=14, fontweight='bold')
axes[2].legend(loc='lower right')
axes[2].axvline(x=0, color='black', linewidth=1)
axes[2].grid(axis='x', alpha=0.5)

plt.tight_layout()
plt.savefig(os.path.join(RESULTADOS_PATH_E3, 'pca_varianza_explicada.png'), dpi=300, bbox_inches='tight')
plt.show()

print(f"\n Gráficas guardadas en: {RESULTADOS_PATH_E3}/pca_varianza_explicada.png")

"""Las gráficas del PCA muestran que los primeros componentes concentran casi toda la información útil del dataset. El PC1 explica cerca del 38% de la varianza y el PC2 alrededor de 25%, lo que significa que entre los dos ya capturan más del 60% del comportamiento de los datos. A partir del cuarto componente, el aporte empieza a ser mucho menor, indicando que las variables adicionales agregan información redundante o poco relevante.

La gráfica de varianza acumulada confirma que con 5 componentes ya se supera el 90% de la varianza total, lo que indica que el dataset es altamente comprimible sin perder estructura significativa. Esto es coherente con el hecho de que varias métricas están correlacionadas entre sí.

Finalmente, el gráfico de contribución a PC1 y PC2 evidencia qué variables son realmente determinantes. PC1 está fuertemente influenciado por métricas de movimiento como velocidad, aceleración y movimiento promedio, mientras que PC2 refleja más aspectos posturales como ángulos articulares e inclinaciones. Esto confirma que el PCA separa de forma natural los dos tipos de información presentes en el dataset: movimiento y postura.
"""

print("SELECCIÓN DE NÚMERO ÓPTIMO DE COMPONENTES")

# Criterios de selección
componentes_80 = np.argmax(varianza_acumulada >= 0.80) + 1
componentes_90 = np.argmax(varianza_acumulada >= 0.90) + 1
componentes_95 = np.argmax(varianza_acumulada >= 0.95) + 1

print(f"\nAnálisis de varianza acumulada:")
print(f"   • {componentes_80} componentes → {varianza_acumulada[componentes_80-1]*100:.2f}% varianza (≥80%)")
print(f"   • {componentes_90} componentes → {varianza_acumulada[componentes_90-1]*100:.2f}% varianza (≥90%)")
print(f"   • {componentes_95} componentes → {varianza_acumulada[componentes_95-1]*100:.2f}% varianza (≥95%)")

# Seleccionar 90% como punto de equilibrio
n_components_selected = componentes_90

print(f"\nDECISIÓN: Seleccionar {n_components_selected} componentes principales")
print(f"   ✓ Conserva {varianza_acumulada[n_components_selected-1]*100:.2f}% de la varianza")
print(f"   ✓ Reduce dimensionalidad de {X_full.shape[1]} → {n_components_selected} características")
print(f"   ✓ Reducción: {(1 - n_components_selected/X_full.shape[1])*100:.1f}%")

print("GENERANDO DATASET REDUCIDO")

# Aplicar PCA con el número de componentes seleccionado
pca_final = PCA(n_components=n_components_selected, random_state=42)
X_pca_reduced = pca_final.fit_transform(X_full)


# Crear DataFrame con componentes principales
columnas_pca = [f'PC{i+1}' for i in range(n_components_selected)]
df_pca = pd.DataFrame(X_pca_reduced, columns=columnas_pca)

# Agregar la columna de categoría
df_pca['categoria'] = y_full.values

print(f"\nDataset reducido creado")
print(f"Dimensiones: {df_pca.shape}")
print(f"Características PCA: {list(df_pca.columns[:-1])}")

# Mostrar primeras filas
print(f"\n Vista previa del dataset reducido:")
display(df_pca.head(10))

# Estadísticas descriptivas
print(f"\nEstadísticas descriptivas de los componentes:")
display(df_pca.describe())

"""El dataset reducido quedó conformado por 86 muestras y 6 componentes principales, lo que confirma que la reducción de dimensionalidad fue efectiva sin perder información relevante. Los componentes PCA presentan medias cercanas a cero, lo que indica que la estandarización y la transformación se aplicaron correctamente, mientras que las desviaciones estándar muestran que PC1 y PC2 concentran mayor variabilidad y, por tanto, más información útil. Además, los rangos de valores son consistentes y no evidencian outliers significativos, lo que sugiere que la proyección a este nuevo espacio es estable. En conjunto, el dataset resultante es más compacto, elimina redundancias y facilita el entrenamiento de modelos de clasificación con datos más limpios y manejables."""

scaler_path_ent2 = "/content/drive/MyDrive/APO3_EntregaFinal/Entrega2/resultados/scaler_minmax_entrega2.pkl"
scaler = joblib.load(scaler_path_ent2)

print("Scaler cargado desde Entrega 2.")

# Guardar dataset reducido
dataset_reducido_path = os.path.join(DATASETS_PATH, "dataset_reducido_pca.csv")
df_pca.to_csv(dataset_reducido_path, index=False)
print(f"\n Dataset reducido guardado en:")
print(f"   {dataset_reducido_path}")

# Guardar objeto PCA para uso futuro
pca_model_path = os.path.join(RESULTADOS_PATH_E3, "pca_model.pkl")
joblib.dump(pca_final, pca_model_path)
print(f"\n Modelo PCA guardado en:")
print(f"   {pca_model_path}")

# Guardar scaler original (para nuevas predicciones)
scaler_path_e3 = os.path.join(RESULTADOS_PATH_E3, "scaler_minmax.pkl")
joblib.dump(scaler, scaler_path_e3)
print(f"\n Scaler guardado en:")
print(f"   {scaler_path_e3}")

print("ANÁLISIS DE INTERPRETACIÓN DE COMPONENTES PRINCIPALES")

# Crear reporte detallado de componentes
for i in range(n_components_selected):
    print(f"\n{'─'*80}")
    print(f"COMPONENTE PRINCIPAL {i+1} (PC{i+1})")
    print(f"{'─'*80}")
    print(f"   Varianza explicada: {pca_final.explained_variance_ratio_[i]*100:.2f}%")
    print(f"   Varianza acumulada: {np.sum(pca_final.explained_variance_ratio_[:i+1])*100:.2f}%")

    # Top 5 features con mayor contribución (loading)
    loadings_pc = pca_final.components_[i]
    feature_importance = pd.DataFrame({
        'Feature': X_full.columns,
        'Loading': loadings_pc,
        'Abs_Loading': np.abs(loadings_pc)
    }).sort_values('Abs_Loading', ascending=False)

    print(f"\n   Top 5 características con mayor contribución:")
    for idx, row in feature_importance.head(5).iterrows():
        signo = "+" if row['Loading'] > 0 else "-"
        print(f"      {signo} {row['Feature']:30s} : {abs(row['Loading']):6.3f}")

print("VISUALIZACIÓN: PROYECCIÓN DE DATOS EN ESPACIO REDUCIDO")

# Crear figura con proyecciones 2D
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Mapa de colores para categorías
categorias_unicas = sorted(y_full.unique())
colores = plt.cm.tab10(np.linspace(0, 1, len(categorias_unicas)))
color_map = dict(zip(categorias_unicas, colores))

# PC1 vs PC2
for categoria in categorias_unicas:
    mask = y_full == categoria
    axes[0].scatter(
        X_pca_reduced[mask, 0],
        X_pca_reduced[mask, 1],
        c=[color_map[categoria]],
        label=categoria,
        s=100,
        alpha=0.7,
        edgecolors='black',
        linewidth=1
    )

axes[0].set_xlabel(f'PC1 ({pca_final.explained_variance_ratio_[0]*100:.1f}% varianza)',
                   fontsize=12, fontweight='bold')
axes[0].set_ylabel(f'PC2 ({pca_final.explained_variance_ratio_[1]*100:.1f}% varianza)',
                   fontsize=12, fontweight='bold')
axes[0].set_title('Proyección de Datos en PC1 vs PC2', fontsize=14, fontweight='bold')
axes[0].legend(loc='best', fontsize=9, framealpha=0.9)
axes[0].grid(True, alpha=0.3)
axes[0].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[0].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# PC2 vs PC3 (si hay al menos 3 componentes)
if n_components_selected >= 3:
    for categoria in categorias_unicas:
        mask = y_full == categoria
        axes[1].scatter(
            X_pca_reduced[mask, 1],
            X_pca_reduced[mask, 2],
            c=[color_map[categoria]],
            label=categoria,
            s=100,
            alpha=0.7,
            edgecolors='black',
            linewidth=1
        )

    axes[1].set_xlabel(f'PC2 ({pca_final.explained_variance_ratio_[1]*100:.1f}% varianza)',
                       fontsize=12, fontweight='bold')
    axes[1].set_ylabel(f'PC3 ({pca_final.explained_variance_ratio_[2]*100:.1f}% varianza)',
                       fontsize=12, fontweight='bold')
    axes[1].set_title('Proyección de Datos en PC2 vs PC3', fontsize=14, fontweight='bold')
    axes[1].legend(loc='best', fontsize=9, framealpha=0.9)
    axes[1].grid(True, alpha=0.3)
    axes[1].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
    axes[1].axvline(x=0, color='k', linestyle='--', linewidth=0.5)
else:
    axes[1].text(0.5, 0.5, 'Menos de 3 componentes\nseleccionados',
                 ha='center', va='center', fontsize=14)
    axes[1].axis('off')

plt.tight_layout()
plt.savefig(os.path.join(RESULTADOS_PATH_E3, 'pca_proyeccion_2d.png'), dpi=300, bbox_inches='tight')
plt.show()

print(f"\nGráfica de proyección guardada en: {RESULTADOS_PATH_E3}/pca_proyeccion_2d.png")

"""En PC1–PC2 se observa que varias categorías, especialmente Adelante, Atrás y Sentadilla, forman grupos bien diferenciados, lo que indica que estos dos componentes capturan gran parte de la variabilidad relevante para separar actividades. Sin embargo, algunas clases como Cadera_Afrente o Tijeras presentan una separación mucho menos clara, reflejando que sus patrones de movimiento son más similares en este espacio reducido.

En PC2–PC3 la separación entre clases es menos marcada, mostrando más mezclas entre categorías. Aun así, se identifica que algunas actividades como Sentadilla y Atrás mantienen cierta cohesión interna. Esta visualización confirma que PC3 aporta información adicional, pero no ofrece tanta discriminación entre clases como PC1–PC2.
"""

print("GENERANDO REPORTE RESUMEN")

reporte_path = os.path.join(RESULTADOS_PATH_E3, "pca_resumen.txt")

with open(reporte_path, 'w', encoding='utf-8') as f:
    f.write("="*80 + "\n")
    f.write("ENTREGA 3 - ANÁLISIS DE COMPONENTES PRINCIPALES (PCA)\n")
    f.write("="*80 + "\n\n")

    f.write("RESUMEN DEL ANÁLISIS\n")
    f.write("-" * 80 + "\n")
    f.write(f"Dataset original:        {X_full.shape[0]} observaciones × {X_full.shape[1]} características\n")
    f.write(f"Dataset reducido (PCA):  {df_pca.shape[0]} observaciones × {n_components_selected} componentes\n")
    f.write(f"Reducción dimensional:   {(1 - n_components_selected/X_full.shape[1])*100:.1f}%\n")
    f.write(f"Varianza conservada:     {varianza_acumulada[n_components_selected-1]*100:.2f}%\n\n")

    f.write("VARIANZA EXPLICADA POR COMPONENTE\n")
    f.write("-" * 80 + "\n")
    for i in range(n_components_selected):
        f.write(f"PC{i+1:2d}: {pca_final.explained_variance_ratio_[i]*100:6.2f}% ")
        f.write(f"(acumulado: {np.sum(pca_final.explained_variance_ratio_[:i+1])*100:6.2f}%)\n")

    f.write("\nINTERPRETACIÓN DE COMPONENTES PRINCIPALES\n")
    f.write("-" * 80 + "\n")
    for i in range(n_components_selected):
        f.write(f"\n▶ PC{i+1}:\n")
        loadings_pc = pca_final.components_[i]
        feature_importance = pd.DataFrame({
            'Feature': X_full.columns,
            'Loading': loadings_pc,
            'Abs_Loading': np.abs(loadings_pc)
        }).sort_values('Abs_Loading', ascending=False)

        f.write("  Top 5 características contribuyentes:\n")
        for idx, row in feature_importance.head(5).iterrows():
            signo = "+" if row['Loading'] > 0 else "-"
            f.write(f"    {signo} {row['Feature']:30s} : {abs(row['Loading']):6.3f}\n")

    f.write("\nCONCLUSIÓN\n")
    f.write("-" * 80 + "\n")
    f.write(f"Se redujo la dimensionalidad de {X_full.shape[1]} a {n_components_selected} componentes,\n")
    f.write(f"conservando el {varianza_acumulada[n_components_selected-1]*100:.2f}% de la varianza original.\n")
    f.write("Esto permite entrenar modelos más simples y eficientes, reduciendo el riesgo\n")
    f.write("de overfitting y mejorando la interpretabilidad del sistema.\n")

print(f"\nReporte resumen guardado en:")
print(f"   {reporte_path}")

print("PARTE 1 COMPLETADA: REDUCCIÓN DE DIMENSIONALIDAD CON PCA")

print(f"\n Archivos generados:")
print(f"   1. Dataset reducido:     {dataset_reducido_path}")
print(f"   2. Modelo PCA:           {pca_model_path}")
print(f"   3. Scaler MinMax:        {scaler_path_e3}")
print(f"   4. Gráfica varianza:     {RESULTADOS_PATH_E3}/pca_varianza_explicada.png")
print(f"   5. Proyección 2D:        {RESULTADOS_PATH_E3}/pca_proyeccion_2d.png")
print(f"   6. Reporte resumen:      {reporte_path}")

print(f"\nSiguiente paso: Parte 2 - Reentrenamiento de modelos con dataset reducido")

"""### **Parte 2: Reentrenamiento y Comparación de Modelos**

## **Objetivos**

1. Reentrenar Random Forest, SVM y XGBoost con el dataset reducido (6 PCs)
2. Utilizar validación cruzada más robusta
3. Comparar métricas entre:
   - Modelos con 12 características (Entrega 2)
   - Modelos con 6 componentes PCA (Entrega 3)
4. Evaluar si la reducción dimensional mantiene o mejora el rendimiento
5. Generar visualizaciones comparativas y conclusiones
"""

# 1. CARGAR DATASET REDUCIDO
print("PARTE 2: REENTRENAMIENTO CON DATASET REDUCIDO")

print("\nCargando dataset reducido con componentes PCA...")
df_pca_loaded = pd.read_csv(dataset_reducido_path)

print(f" Dataset reducido cargado:")
print(f"   Dimensiones: {df_pca_loaded.shape}")
print(f"   Características: {list(df_pca_loaded.columns[:-1])}")
print(f"   Clases: {df_pca_loaded['categoria'].nunique()}")

# Separar características y etiquetas
X_pca = df_pca_loaded.drop(columns=['categoria'])
y_pca = df_pca_loaded['categoria']

# Codificar etiquetas (mismo encoder que antes)
y_pca_encoded = label_encoder_e3.transform(y_pca)

# 2. DIVISIÓN TRAIN/TEST (MISMO RANDOM_STATE PARA COMPARACIÓN JUSTA)
print("\nDivisión train/test (80/20, stratified, random_state=42)...")
X_pca_train, X_pca_test, y_pca_train, y_pca_test = train_test_split(
    X_pca, y_pca_encoded,
    test_size=0.2,
    random_state=42,  # ← MISMO que Entrega 2 para comparación justa
    stratify=y_pca_encoded
)

print(f"División completada:")
print(f"   Train: {X_pca_train.shape[0]} muestras")
print(f"   Test:  {X_pca_test.shape[0]} muestras")

# 3. DEFINIR GRIDS DE HIPERPARÁMETROS (MISMOS QUE ENTREGA 2)
print("\nConfigurando búsqueda de hiperparámetros...")

# Random Forest
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10]
}

# SVM
param_grid_svm = {
    'C': [0.1, 1, 10],
    'gamma': ['scale', 0.01, 0.001],
    'kernel': ['rbf']
}

# XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1]
}

print("Grids configurados (mismos parámetros que Entrega 2)")

# 4. ENTRENAR MODELOS CON GRIDSEARCHCV
print("ENTRENANDO MODELOS CON DATASET REDUCIDO (6 PCs)")

resultados_e3 = []

# --- RANDOM FOREST ---
print("\n 1. Random Forest con GridSearchCV...")
grid_rf_e3 = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid_rf,
    cv=5,  # Usamos cv=5 para validación más robusta
    n_jobs=-1,
    scoring='accuracy',
    verbose=1
)
grid_rf_e3.fit(X_pca_train, y_pca_train)
best_rf_e3 = grid_rf_e3.best_estimator_

print(f"    Mejores hiperparámetros: {grid_rf_e3.best_params_}")
print(f"    Mejor CV score: {grid_rf_e3.best_score_*100:.2f}%")

# --- SVM ---
print("\n 2. SVM (RBF) con GridSearchCV...")
grid_svm_e3 = GridSearchCV(
    SVC(random_state=42),
    param_grid_svm,
    cv=5,
    n_jobs=-1,
    scoring='accuracy',
    verbose=1
)
grid_svm_e3.fit(X_pca_train, y_pca_train)
best_svm_e3 = grid_svm_e3.best_estimator_

print(f"    Mejores hiperparámetros: {grid_svm_e3.best_params_}")
print(f"    Mejor CV score: {grid_svm_e3.best_score_*100:.2f}%")

# XGBOOST
print("\n 3. XGBoost con GridSearchCV...")
grid_xgb_e3 = GridSearchCV(
    XGBClassifier(
        eval_metric='mlogloss',
        random_state=42,
        use_label_encoder=False
    ),
    param_grid_xgb,
    cv=5,
    n_jobs=-1,
    scoring='accuracy',
    verbose=1
)
grid_xgb_e3.fit(X_pca_train, y_pca_train)
best_xgb_e3 = grid_xgb_e3.best_estimator_

print(f"    Mejores hiperparámetros: {grid_xgb_e3.best_params_}")
print(f"    Mejor CV score: {grid_xgb_e3.best_score_*100:.2f}%")

"""Los modelos entrenados con el dataset reducido muestran un rendimiento sobresaliente, lo que confirma que la reducción dimensional no afectó negativamente la capacidad de clasificación. El SVM con kernel RBF obtuvo el mejor desempeño con un 100% de accuracy en validación cruzada, indicando una excelente separación entre actividades en el espacio transformado por PCA. El Random Forest también logró una precisión muy alta (98.46%), demostrando buena estabilidad con un modelo menos sensible a escalamiento. Por su parte, XGBoost alcanzó 97.03%, ligeramente menor pero aún indicando una fuerte capacidad predictiva. En conjunto, los resultados muestran que el espacio reducido a 6 PCs conserva información suficiente para entrenar clasificadores robustos y eficientes, validando la elección óptima de componentes."""

# 5. EVALUACIÓN EN TEST SET
print("EVALUACIÓN EN TEST SET (Dataset Reducido)")

modelos_e3 = {
    "Random Forest": best_rf_e3,
    "SVM (RBF)": best_svm_e3,
    "XGBoost": best_xgb_e3
}

for nombre, modelo in modelos_e3.items():
    print(f"\n{'─'*80}")
    print(f"{nombre} (6 PCs)")
    print(f"{'─'*80}")

    # Predicciones
    y_pred = modelo.predict(X_pca_test)

    # Métricas
    from sklearn.metrics import precision_score, recall_score, f1_score

    acc = accuracy_score(y_pca_test, y_pred)
    precision = precision_score(y_pca_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_pca_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_pca_test, y_pred, average='weighted', zero_division=0)

    # Guardar resultados
    resultados_e3.append({
        'Modelo': nombre,
        'Features': '6 PCs',
        'Accuracy': acc,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'CV Score': grid_rf_e3.best_score_ if nombre == "Random Forest" else
                    (grid_svm_e3.best_score_ if nombre == "SVM (RBF)" else grid_xgb_e3.best_score_)
    })

    print(f"\n   Accuracy:  {acc*100:6.2f}%")
    print(f"   Precision: {precision*100:6.2f}%")
    print(f"   Recall:    {recall*100:6.2f}%")
    print(f"   F1-Score:  {f1*100:6.2f}%")

    # Classification report
    print(f"\n   Reporte detallado por clase:")
    print(classification_report(y_pca_test, y_pred,
                                target_names=label_encoder_e3.classes_,
                                zero_division=0))

    # Matriz de confusión
    cm = confusion_matrix(y_pca_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder_e3.classes_,
                yticklabels=label_encoder_e3.classes_)
    plt.title(f'Matriz de Confusión - {nombre} (6 PCs)\nEntrega 3',
              fontsize=14, fontweight='bold')
    plt.xlabel('Predicción', fontweight='bold')
    plt.ylabel('Real', fontweight='bold')
    plt.tight_layout()

    filename = nombre.lower().replace(' ', '_').replace('(', '').replace(')', '')
    plt.savefig(os.path.join(RESULTADOS_PATH_E3, f'confusion_matrix_{filename}_pca.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    print(f"   Matriz de confusión guardada")

# 6. COMPARACIÓN CON ENTREGA 2
print("COMPARACIÓN: ENTREGA 2 (12 features) vs ENTREGA 3 (6 PCs)")

# Resultados de Entrega 2 (del notebook/html)
resultados_e2 = [
    {'Modelo': 'Random Forest', 'Features': '12 original', 'Accuracy': 1.00,
     'Precision': 1.00, 'Recall': 1.00, 'F1-Score': 1.00, 'CV Score': 1.00},
    {'Modelo': 'SVM (RBF)', 'Features': '12 original', 'Accuracy': 1.00,
     'Precision': 1.00, 'Recall': 1.00, 'F1-Score': 1.00, 'CV Score': 1.00},
    {'Modelo': 'XGBoost', 'Features': '12 original', 'Accuracy': 0.889,
     'Precision': 0.944, 'Recall': 0.889, 'F1-Score': 0.873, 'CV Score': 0.889}
]

# Combinar resultados
df_comparacion = pd.concat([
    pd.DataFrame(resultados_e2),
    pd.DataFrame(resultados_e3)
], ignore_index=True)

print("\nTabla Comparativa:")
print(df_comparacion.to_string(index=False))

# Guardar tabla comparativa
csv_comparacion_path = os.path.join(RESULTADOS_PATH_E3, "comparacion_modelos.csv")
df_comparacion.to_csv(csv_comparacion_path, index=False)
print(f"\nTabla comparativa guardada en: {csv_comparacion_path}")

# 7. VISUALIZACIONES COMPARATIVAS

print("\nGenerando visualizaciones comparativas...")

# Configuración
sns.set_style("whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

modelos_unicos = ['Random Forest', 'SVM (RBF)', 'XGBoost']
colors_e2 = '#3498db'
colors_e3 = '#e74c3c'

# Plot 1: Accuracy Comparison
ax = axes[0, 0]
x_pos = np.arange(len(modelos_unicos))
width = 0.35

acc_e2 = [df_comparacion[(df_comparacion['Modelo']==m) & (df_comparacion['Features']=='12 original')]['Accuracy'].values[0]
          for m in modelos_unicos]
acc_e3 = [df_comparacion[(df_comparacion['Modelo']==m) & (df_comparacion['Features']=='6 PCs')]['Accuracy'].values[0]
          for m in modelos_unicos]

ax.bar(x_pos - width/2, acc_e2, width, label='Entrega 2 (12 features)',
       color=colors_e2, alpha=0.8, edgecolor='black')
ax.bar(x_pos + width/2, acc_e3, width, label='Entrega 3 (6 PCs)',
       color=colors_e3, alpha=0.8, edgecolor='black')

ax.set_xlabel('Modelo', fontweight='bold', fontsize=12)
ax.set_ylabel('Accuracy', fontweight='bold', fontsize=12)
ax.set_title('Comparación de Accuracy: E2 vs E3', fontweight='bold', fontsize=14)
ax.set_xticks(x_pos)
ax.set_xticklabels(modelos_unicos, rotation=15, ha='right')
ax.set_ylim([0.5, 1.05])
ax.legend()
ax.grid(axis='y', alpha=0.3)

for i, (v2, v3) in enumerate(zip(acc_e2, acc_e3)):
    ax.text(i - width/2, v2 + 0.02, f'{v2:.2f}', ha='center', va='bottom', fontweight='bold')
    ax.text(i + width/2, v3 + 0.02, f'{v3:.2f}', ha='center', va='bottom', fontweight='bold')

# Plot 2: F1-Score Comparison
ax = axes[0, 1]
f1_e2 = [df_comparacion[(df_comparacion['Modelo']==m) & (df_comparacion['Features']=='12 original')]['F1-Score'].values[0]
         for m in modelos_unicos]
f1_e3 = [df_comparacion[(df_comparacion['Modelo']==m) & (df_comparacion['Features']=='6 PCs')]['F1-Score'].values[0]
         for m in modelos_unicos]

ax.bar(x_pos - width/2, f1_e2, width, label='Entrega 2 (12 features)',
       color=colors_e2, alpha=0.8, edgecolor='black')
ax.bar(x_pos + width/2, f1_e3, width, label='Entrega 3 (6 PCs)',
       color=colors_e3, alpha=0.8, edgecolor='black')

ax.set_xlabel('Modelo', fontweight='bold', fontsize=12)
ax.set_ylabel('F1-Score', fontweight='bold', fontsize=12)
ax.set_title('Comparación de F1-Score: E2 vs E3', fontweight='bold', fontsize=14)
ax.set_xticks(x_pos)
ax.set_xticklabels(modelos_unicos, rotation=15, ha='right')
ax.set_ylim([0.5, 1.05])
ax.legend()
ax.grid(axis='y', alpha=0.3)

for i, (v2, v3) in enumerate(zip(f1_e2, f1_e3)):
    ax.text(i - width/2, v2 + 0.02, f'{v2:.2f}', ha='center', va='bottom', fontweight='bold')
    ax.text(i + width/2, v3 + 0.02, f'{v3:.2f}', ha='center', va='bottom', fontweight='bold')

# Plot 3: Diferencia Relativa (%)
ax = axes[1, 0]
diff_acc = [(e3 - e2) * 100 for e2, e3 in zip(acc_e2, acc_e3)]
colors_diff = ['green' if d >= 0 else 'red' for d in diff_acc]

ax.bar(x_pos, diff_acc, color=colors_diff, alpha=0.7, edgecolor='black', linewidth=1.5)
ax.axhline(y=0, color='black', linestyle='--', linewidth=2)
ax.set_xlabel('Modelo', fontweight='bold', fontsize=12)
ax.set_ylabel('Diferencia de Accuracy (%)', fontweight='bold', fontsize=12)
ax.set_title('Cambio en Accuracy: E3 - E2\n(Positivo = Mejora con PCA)',
             fontweight='bold', fontsize=14)
ax.set_xticks(x_pos)
ax.set_xticklabels(modelos_unicos, rotation=15, ha='right')
ax.grid(axis='y', alpha=0.3)

for i, v in enumerate(diff_acc):
    va = 'bottom' if v >= 0 else 'top'
    offset = 1 if v >= 0 else -1
    ax.text(i, v + offset, f'{v:+.1f}%', ha='center', va=va, fontweight='bold')

# Plot 4: Resumen en Tabla
ax = axes[1, 1]
ax.axis('off')

resumen_text = f"""
╔═══════════════════════════════════════════════════════════╗
║     RESUMEN COMPARATIVO: ENTREGA 2 vs ENTREGA 3          ║
╚═══════════════════════════════════════════════════════════╝

DATASET:
   • Entrega 2: 12 características originales
   • Entrega 3: 6 componentes principales (PCA)
   • Reducción: 50% en dimensionalidad
   • Varianza conservada: 91.73%

RESULTADOS PROMEDIO:

   Entrega 2 (12 features):
      Accuracy:  {np.mean(acc_e2)*100:.1f}%
      F1-Score:  {np.mean(f1_e2)*100:.1f}%

   Entrega 3 (6 PCs):
      Accuracy:  {np.mean(acc_e3)*100:.1f}%
      F1-Score:  {np.mean(f1_e3)*100:.1f}%

   Diferencia:  {(np.mean(acc_e3) - np.mean(acc_e2))*100:+.1f}%

CONCLUSIÓN:

   La reducción dimensional con PCA permite:
   • Reducir complejidad (50% menos features)
   • Mantener rendimiento comparable
   • Reducir riesgo de overfitting
   • Mejorar eficiencia computacional

   {' PCA mejoró el rendimiento' if np.mean(acc_e3) > np.mean(acc_e2) else
    '  Leve caída esperada por regularización' if abs(np.mean(acc_e3) - np.mean(acc_e2)) < 0.05 else
    'Caída significativa, revisar componentes'}

╚═══════════════════════════════════════════════════════════╝
"""

ax.text(0.05, 0.95, resumen_text,
        transform=ax.transAxes,
        fontsize=10,
        verticalalignment='top',
        fontfamily='monospace',
        bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.3))

plt.tight_layout()
plt.savefig(os.path.join(RESULTADOS_PATH_E3, 'comparacion_general_e2_vs_e3.png'),
            dpi=300, bbox_inches='tight')
plt.show()

print("Visualizaciones guardadas")

# 8. GENERAR REPORTE FINAL
print("\n" + "="*80)
print("GENERANDO REPORTE FINAL")
print("="*80)

reporte_final_path = os.path.join(RESULTADOS_PATH_E3, "reporte_final_entrega3.txt")

with open(reporte_final_path, 'w', encoding='utf-8') as f:
    f.write("="*80 + "\n")
    f.write("ENTREGA 3 - REPORTE FINAL\n")
    f.write("Sistema de Análisis de Movimiento Humano\n")
    f.write("="*80 + "\n\n")

    f.write("RESUMEN EJECUTIVO\n")
    f.write("-"*80 + "\n\n")
    f.write("Este reporte compara el rendimiento de modelos de clasificación\n")
    f.write("entrenados con características originales (Entrega 2) versus\n")
    f.write("características reducidas mediante PCA (Entrega 3).\n\n")

    f.write("OBJETIVO\n")
    f.write("-"*80 + "\n")
    f.write("• Reducir dimensionalidad del espacio de características\n")
    f.write("• Mantener o mejorar el rendimiento de clasificación\n")
    f.write("• Reducir overfitting y mejorar generalización\n")
    f.write("• Optimizar eficiencia computacional\n\n")

    f.write("RESULTADOS PCA\n")
    f.write("-"*80 + "\n")
    f.write(f"• Características originales:     12\n")
    f.write(f"• Componentes principales:        6\n")
    f.write(f"• Reducción dimensional:          50.0%\n")
    f.write(f"• Varianza explicada conservada:  91.73%\n\n")

    f.write("COMPARACIÓN DE MODELOS\n")
    f.write("-"*80 + "\n\n")

    for modelo in modelos_unicos:
        f.write(f"▶ {modelo}\n")
        f.write(f"  {'─'*76}\n")

        # Entrega 2
        e2_data = df_comparacion[(df_comparacion['Modelo']==modelo) &
                                 (df_comparacion['Features']=='12 original')].iloc[0]
        f.write(f"  Entrega 2 (12 features):\n")
        f.write(f"    • Accuracy:   {e2_data['Accuracy']*100:6.2f}%\n")
        f.write(f"    • Precision:  {e2_data['Precision']*100:6.2f}%\n")
        f.write(f"    • Recall:     {e2_data['Recall']*100:6.2f}%\n")
        f.write(f"    • F1-Score:   {e2_data['F1-Score']*100:6.2f}%\n\n")

        # Entrega 3
        e3_data = df_comparacion[(df_comparacion['Modelo']==modelo) &
                                 (df_comparacion['Features']=='6 PCs')].iloc[0]
        f.write(f"  Entrega 3 (6 PCs):\n")
        f.write(f"    • Accuracy:   {e3_data['Accuracy']*100:6.2f}%\n")
        f.write(f"    • Precision:  {e3_data['Precision']*100:6.2f}%\n")
        f.write(f"    • Recall:     {e3_data['Recall']*100:6.2f}%\n")
        f.write(f"    • F1-Score:   {e3_data['F1-Score']*100:6.2f}%\n\n")

        # Diferencia
        diff = (e3_data['Accuracy'] - e2_data['Accuracy']) * 100
        f.write(f"  Diferencia:   {diff:+.2f}%\n")
        if diff > 0:
            f.write(f"  Estado:       Mejora con PCA\n\n")
        elif abs(diff) < 5:
            f.write(f"  Estado:       Rendimiento mantenido\n\n")
        else:
            f.write(f"  Estado:       Caída por regularización\n\n")

    f.write("\n ESTADÍSTICAS GENERALES\n")
    f.write("-"*80 + "\n")
    f.write(f"Accuracy promedio E2:  {np.mean(acc_e2)*100:.2f}%\n")
    f.write(f"Accuracy promedio E3:  {np.mean(acc_e3)*100:.2f}%\n")
    f.write(f"Diferencia promedio:   {(np.mean(acc_e3) - np.mean(acc_e2))*100:+.2f}%\n\n")

    f.write(f"F1-Score promedio E2:  {np.mean(f1_e2)*100:.2f}%\n")
    f.write(f"F1-Score promedio E3:  {np.mean(f1_e3)*100:.2f}%\n")
    f.write(f"Diferencia promedio:   {(np.mean(f1_e3) - np.mean(f1_e2))*100:+.2f}%\n\n")

    f.write("\ CONCLUSIONES\n")
    f.write("-"*80 + "\n\n")

    f.write("1. REDUCCIÓN DIMENSIONAL EXITOSA\n")
    f.write("   • Se logró reducir de 12 a 6 características (50%)\n")
    f.write("   • Se conservó 91.73% de la varianza original\n")
    f.write("   • El modelo es más eficiente computacionalmente\n\n")

    f.write("2. RENDIMIENTO DE MODELOS\n")
    if np.mean(acc_e3) >= np.mean(acc_e2) * 0.95:
        f.write("   • El rendimiento se mantuvo comparable o mejoró\n")
        f.write("   • PCA actuó como regularización efectiva\n")
    else:
        f.write("   • Leve reducción en rendimiento esperada\n")
        f.write("   • Trade-off razonable: -50% features, -X% accuracy\n")
    f.write("   • Los modelos son más robustos y generalizables\n\n")

    f.write("3. PROBLEMA DE OVERFITTING IDENTIFICADO\n")
    f.write("   • Los resultados de 100% en E2 sugieren overfitting\n")
    f.write("   • Dataset muy pequeño (86 muestras, 8 clases)\n")
    f.write("   • PCA ayuda a mitigar este problema\n")
    f.write("   • Se necesitan más datos para validación externa\n\n")

    f.write("4. RECOMENDACIONES FUTURAS\n")
    f.write("   • Recolectar más videos (objetivo: 200+ por clase)\n")
    f.write("   • Validar con personas diferentes a las del training\n")
    f.write("   • Considerar data augmentation\n")
    f.write("   • Explorar otras técnicas (LDA, t-SNE)\n")
    f.write("   • Implementar sistema en tiempo real\n\n")

    f.write("\n" + "="*80 + "\n")
    f.write("FIN DEL REPORTE\n")
    f.write("="*80 + "\n")

print(f"Reporte final guardado en: {reporte_final_path}")

# 9. RESUMEN FINAL

print("\n" + "="*80)
print(" ENTREGA 3 COMPLETADA")
print("="*80)

print(f"\n Archivos generados:")
print(f"\n   PARTE 1 - PCA:")
print(f"   1. {dataset_reducido_path}")
print(f"   2. {pca_model_path}")
print(f"   3. {scaler_path_e3}")
print(f"   4. {RESULTADOS_PATH_E3}/pca_varianza_explicada.png")
print(f"   5. {RESULTADOS_PATH_E3}/pca_proyeccion_2d.png")
print(f"   6. {reporte_path}")

print(f"\n   PARTE 2 - REENTRENAMIENTO:")
print(f"   7. {csv_comparacion_path}")
print(f"   8. {RESULTADOS_PATH_E3}/comparacion_general_e2_vs_e3.png")
print(f"   9. {RESULTADOS_PATH_E3}/confusion_matrix_random_forest_pca.png")
print(f"  10. {RESULTADOS_PATH_E3}/confusion_matrix_svm_rbf_pca.png")
print(f"  11. {RESULTADOS_PATH_E3}/confusion_matrix_xgboost_pca.png")
print(f"  12. {reporte_final_path}")

print(f"\n RESUMEN:")
print(f"   • Reducción dimensional: 12 → 6 características (50%)")
print(f"   • Varianza conservada: 91.73%")
print(f"   • Modelos entrenados: Random Forest, SVM, XGBoost")
print(f"   • Comparación completa E2 vs E3 generada")
print(f"   • Matrices de confusión y métricas guardadas")

print("\n" + "="*80)
print(" El proyecto está listo para ser presentado!")
print("="*80 + "\n")

# GUARDAR MODELOS ENTRENADOS DE ENTREGA 3 (con 6 PCs)
# ESTO SE DEBE EJECUTAR ESTO AL FINAL DEL NOTEBOOK, después de entrenar los modelos

import joblib
import os

print(" GUARDANDO MODELOS DE ENTREGA 3")

# Ruta donde guardarás los modelos
RESULTADOS_PATH_E3 = "/content/drive/MyDrive/APO3_EntregaFinal/Entrega3/resultados"

# Verificar que las variables existen
print("\n Verificando modelos disponibles...")
try:
    print(f"    best_rf_e3: {type(best_rf_e3)}")
    print(f"    best_svm_e3: {type(best_svm_e3)}")
    print(f"    best_xgb_e3: {type(best_xgb_e3)}")
    print(f"    label_encoder_e3: {type(label_encoder_e3)}")
except NameError as e:
    print(f"    Error: {e}")
    print("     Asegúrate de haber ejecutado el entrenamiento primero!")

# Guardar modelos
print("\n Guardando modelos...")

joblib.dump(best_rf_e3, os.path.join(RESULTADOS_PATH_E3, "random_forest_model.pkl"))
print("    Random Forest (6 PCs) guardado")

joblib.dump(best_svm_e3, os.path.join(RESULTADOS_PATH_E3, "svm_model.pkl"))
print("    SVM (6 PCs) guardado")

joblib.dump(best_xgb_e3, os.path.join(RESULTADOS_PATH_E3, "xgboost_model.pkl"))
print("    XGBoost (6 PCs) guardado")

joblib.dump(label_encoder_e3, os.path.join(RESULTADOS_PATH_E3, "label_encoder.pkl"))
print("    Label Encoder guardado")

print("\n ¡Todos los modelos de Entrega 3 guardados correctamente!")
print(f" Ubicación: {RESULTADOS_PATH_E3}")

# Verificar que fueron guardados con el número correcto de features
print("\n Verificando características de los modelos...")
print(f"   Random Forest espera {best_rf_e3.n_features_in_} features")
print(f"   SVM espera {best_svm_e3.n_features_in_} features")
print(f"   XGBoost espera {best_xgb_e3.n_features_in_} features")
print("\n    Deberían ser 6 features (componentes PCA)")

# Commented out IPython magic to ensure Python compatibility.
# %whos

"""
Script para reentrenar SVM con probability=True
"""

import joblib
import os
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

print(" REENTRENANDO SVM CON PROBABILIDADES")

# Configuración de rutas
RESULTADOS_PATH_E3 = "/content/drive/MyDrive/APO3_EntregaFinal/Entrega3/resultados"

# Grid de hiperparámetros (igual que antes)
param_grid_svm = {
    'C': [0.1, 1, 10],
    'gamma': ['scale', 0.01, 0.001],
    'kernel': ['rbf']
}

print("\n Reentrenando SVM con probability=True...")
print("   (Esto puede tomar un poco más de tiempo)")

# Entrenar con probability=True
grid_svm_prob = GridSearchCV(
    SVC(random_state=42, probability=True),  # ← probability=True
    param_grid_svm,
    cv=5,
    n_jobs=-1,
    scoring='accuracy',
    verbose=1
)
grid_svm_prob.fit(X_pca_train, y_pca_train)
best_svm_prob = grid_svm_prob.best_estimator_

print(f"\n Mejores hiperparámetros: {grid_svm_prob.best_params_}")
print(f" Mejor CV score: {grid_svm_prob.best_score_*100:.2f}%")

# Evaluar en test
from sklearn.metrics import accuracy_score
y_pred_test = best_svm_prob.predict(X_pca_test)
acc_test = accuracy_score(y_pca_test, y_pred_test)
print(f" Test accuracy: {acc_test*100:.2f}%")

# Verificar que ahora sí tiene probabilidades
print("\n Verificando predict_proba...")
try:
    proba_test = best_svm_prob.predict_proba(X_pca_test[:1])
    print(f"    predict_proba funciona correctamente!")
    print(f"   Probabilidades de ejemplo: {proba_test[0][:3]}")
except:
    print(f"    Error: predict_proba no disponible")

# Guardar modelo actualizado
print("\n Guardando modelo SVM con probabilidades...")
joblib.dump(best_svm_prob, os.path.join(RESULTADOS_PATH_E3, "svm_model.pkl"))
print(f"    Guardado en: {RESULTADOS_PATH_E3}/svm_model.pkl")

print(" ¡SVM reentrenado con probabilidades!")

"""### Análisis final del impacto de la solución

El sistema desarrollado demuestra que es posible clasificar actividades humanas usando únicamente video, landmarks de MediaPipe y modelos supervisados, sin requerir sensores ni equipos especializados. Esto tiene un impacto directo en varios aspectos. En el contexto académico, la solución facilita que estudiantes e investigadores exploren análisis biomecánico utilizando herramientas accesibles, permitiendo estudiar patrones de movimiento desde un enfoque computacional. El uso de PCA para reducir dimensionalidad también vuelve el proceso más eficiente, lo que abre la puerta a experimentos más complejos sin depender de hardware de alto costo.

En un conexto práctico, este tipo de sistema puede apoyar procesos como prevención de lesiones, seguimiento de rehabilitación o evaluación técnica en ejercicios. El hecho de que los modelos mantengan un rendimiento cercano al 100% incluso después de la reducción a seis componentes principales demuestra que la solución es estable y escalable, lo que la hace viable para incorporarla en entornos reales, desde clases de educación física hasta análisis ergonómico en lugares de trabajo.

Finalmente, el proyecto tiene un impacto futuro significativo: al estar basado en cámaras RGB comunes y modelos livianos, puede evolucionar hacia aplicaciones móviles que analicen movimientos en tiempo real. También podría complementarse con módulos de retroalimentación automática para corregir posturas o detectar riesgos biomecánicos. En conclusión, el desarrollo no solo resuelve el problema planteado, sino que también establece una base sólida para aplicaciones educativas, clínicas y deportivas en escenarios donde normalmente no se tiene acceso a tecnologías avanzadas de captura de movimiento.
"""